### ISSUE TITLE
Curious to know more about your project

### ISSUE THREAD

**Issue by CTanguay-Sabourin** [mtl-brainhack-school-2019/Nick#1]
Doing both research and clinic must be intense, but we're all here to learn. I might do a bibliography as well on my own .md, it's a good idea.

**Comment by nickcorriveaul** [comment]
It is a bit challenging indeed ;). But very enriching both intellectually and humanly speaking. Thanks for the comment on my biography (credits to Anthony Gifuni from whom I stole the idea).
